name: Cypress Main Workflow

on:
  workflow_call:
    inputs:
      spec_file:
        required: true
        type: string
      team:
        required: true
        type: string

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate Readable RunID
        id: runid
        run: |
          # Generate RunID in the desired format (YYYYMMDD-HHMMSS)
          SAFE_RUNID=$(date -u +'%Y%m%d-%H%M%S')  # Format without dashes and underscores
          READABLE_DATE=$(date -u +'%B %d, %Y')   # "March 18, 2025"
          UTC_TIME=$(date -u +'%H:%M:%S UTC')     # "14:05:22 UTC"
          EST_TIME=$(TZ="America/New_York" date +'%I:%M %p EST')  # "09:35 AM EST"
          IST_TIME=$(TZ="Asia/Kolkata" date +'%I:%M %p IST')  # "08:05 PM IST"
          echo "runID=$SAFE_RUNID" >> $GITHUB_ENV
          echo "readableDate=$READABLE_DATE" >> $GITHUB_ENV
          echo "utcTime=$UTC_TIME" >> $GITHUB_ENV
          echo "estTime=$EST_TIME" >> $GITHUB_ENV
          echo "istTime=$IST_TIME" >> $GITHUB_ENV

      - name: Run Cypress tests for ${{ inputs.team }}
        continue-on-error: true
        run: npx cypress run --spec "cypress/e2e/${{ inputs.spec_file }}"

      - name: Setup GitHub Pages directory
        run: |
          mkdir -p gh-pages
          cd gh-pages
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch origin gh-pages --depth=1
          git checkout gh-pages || echo "No gh-pages branch yet"
          cd ..

      - name: Prepare report for GitHub Pages
        run: |
          mkdir -p gh-pages/${{ inputs.team }}/${{ env.runID }}
          cp -r cypress/reports/html/* gh-pages/${{ inputs.team }}/${{ env.runID }}/

      - name: Generate Main Index Page
        run: |
          echo "<!DOCTYPE html>
          <html>
          <head>
            <title>Cypress Test Reports</title>
            <style>
              @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap');
              body {
                font-family: 'Poppins', sans-serif;
                background-color: #f4f4f9;
                text-align: center;
                margin: 0;
                padding: 0;
              }
              h1 {
                font-size: 40px;
                font-weight: 600;
                color: #222;
                text-transform: uppercase;
                text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.2);
                background: linear-gradient(45deg, #ff6b6b, #f06595, #845ef7);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
                margin-top: 20px;
              }
              h2 {
                font-size: 22px;
                color: #333;
                font-weight: 400;
                margin-top: -10px;
                opacity: 0.8;
              }
              .container {
                max-width: 800px;
                margin: 40px auto;
                padding: 20px;
              }
              .team-cards {
                display: flex;
                justify-content: center;
                gap: 30px;
              }
              .card {
                width: 250px;
                height: 200px;
                background: white;
                box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
                border-radius: 10px;
                display: flex;
                flex-direction: column;
                align-items: center;
                justify-content: center;
                transition: 0.3s;
                text-decoration: none;
                color: black;
                font-size: 18px;
                font-weight: bold;
              }
              .card:hover {
                transform: scale(1.05);
                box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.2);
              }
              .abc { background-color: #28a745; color: white; }
              .xyz { background-color: #007bff; color: white; }
              .footer {
                margin-top: 20px;
                font-size: 14px;
                color: #666;
              }
            </style>
          </head>
          <body>
            <div class='container'>
              <h1>🚀 Cypress Test Reports</h1>
              <h2>Select a team to view test reports:</h2>
              <div class='team-cards'>
                <a href='./abc/' class='card abc'>📌 Team ABC</a>
                <a href='./xyz/' class='card xyz'>📌 Team XYZ</a>
              </div>
              <div class='footer'>Generated by GitHub Actions</div>
            </div>
          </body>
          </html>" > gh-pages/index.html

          - name: Generate Team Report Page
          run: |
            for team in abc xyz; do
            echo "<!DOCTYPE html>
            <html>
            <head>
              <title>${team^^} Test Reports</title>
              <style>
                @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap');
                body {
                  font-family: 'Poppins', sans-serif;
                  background-color: #f4f4f9;
                  text-align: center;
                  margin: 0;
                  padding: 0;
                }
                h1 {
                  font-size: 36px;
                  font-weight: 600;
                  color: #222;
                  text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.2);
                  background: linear-gradient(45deg, #17a2b8, #007bff);
                  -webkit-background-clip: text;
                  -webkit-text-fill-color: transparent;
                  margin-top: 20px;
                }
                h2 {
                  font-size: 20px;
                  color: #555;
                  font-weight: 400;
                  opacity: 0.8;
                }
                .container {
                  max-width: 800px;
                  margin: 40px auto;
                  padding: 20px;
                }
                .reports {
                  display: flex;
                  flex-wrap: wrap;
                  justify-content: center;
                  gap: 20px;
                }
                .report-card {
                  width: 280px;
                  height: 100px;
                  background: white;
                  box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);
                  border-radius: 8px;
                  display: flex;
                  flex-direction: column;
                  align-items: center;
                  justify-content: center;
                  font-size: 16px;
                  font-weight: bold;
                  transition: 0.3s;
                  text-decoration: none;
                  color: white;
                  background-color: #28a745;
                  border-left: 5px solid #155724;
                  padding: 10px;
                }
                .report-card:hover {
                  transform: scale(1.05);
                  box-shadow: 0px 4px 12px rgba(0, 0, 0, 0.2);
                  background-color: #218838;
                }
                .timestamp {
                  font-size: 14px;
                  color: #666;
                  margin-top: 4px;
                }
                .back-btn {
                  display: inline-block;
                  margin-top: 20px;
                  padding: 10px 20px;
                  font-size: 14px;
                  text-decoration: none;
                  color: white;
                  background: #007bff;
                  border-radius: 5px;
                  transition: 0.3s;
                }
                .back-btn:hover { background: #0056b3; }
              </style>
            </head>
            <body>
              <div class='container'>
                <h1>🦸 ${team^^} Test Reports</h1>
                <h2>Select a test run to view the report:</h2>
                <div class='reports'>" > gh-pages/${team}/index.html
        
            for dir in $(ls -d gh-pages/${team}/*/ | sort -r); do
              runID=$(basename "$dir")
              
              # Convert runID to the previous format (YYYY-MM-DD HH:MM:SS)
              formattedRunID=$(echo "$runID" | sed 's/\(..\)\(..\)\(..\)-\(..\)\(..\)\(..\)/\1-\2-\3 \4\5\6/')
        
              # Generate the times in UTC, EST, and IST
              UTC_TIME=$(date -u -d "$formattedRunID" +'%H:%M:%S UTC')
              EST_TIME=$(TZ="America/New_York" date -d "$formattedRunID" +'%I:%M %p EST')
              IST_TIME=$(TZ="Asia/Kolkata" date -d "$formattedRunID" +'%I:%M %p IST')
        
              # Output the times to GitHub environment variables
              echo "utcTime=$UTC_TIME" >> $GITHUB_ENV
              echo "estTime=$EST_TIME" >> $GITHUB_ENV
              echo "istTime=$IST_TIME" >> $GITHUB_ENV
        
              # Adding report link for each runID
              echo "<a href='./$runID/' class='report-card'>
                      📝 Run ID: $runID
                      <div class='timestamp'>$UTC_TIME | $EST_TIME | $IST_TIME</div>
                    </a>" >> gh-pages/${team}/index.html
            done
        
            echo "</div>
                <a href='../' class='back-btn'>⬅️ Back to Teams</a>
              </div>
            </body>
            </html>" >> gh-pages/${team}/index.html
              done
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
          keep_files: true


          