name: Cypress Tests for XYZ

on:

  workflow_dispatch:
    inputs:
      trigger:  # Optional input to provide custom message for triggering
        description: 'Trigger xyz Tests'
        required: true
        default: 'yes'

jobs:
  xyz-tests:
    uses: ./.github/workflows/cypress-main.yml
    with:
      spec_file: "xyz_practice-login.cy.js"
      team: "xyz"
