name: Cypress Tests for ABC

concurrency:
  group: "gh-pages-${{ github.ref }}"
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Trigger ABC Tests'
        required: true
        default: 'yes'

jobs:
  abc-tests:
    uses: ./.github/workflows/cypress-main.yml
    with:
      spec_file: "abc_practice-login.cy.js"
      team: "abc"
