name: Cypress Main Workflow

on:
  workflow_call:
    inputs:
      spec_file:
        required: true
        type: string
      team:
        required: true
        type: string

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate Readable RunID
        id: runid
        run: |
          # Generate RunID in the desired format (YYYYMMDD-HHMMSS)
          SAFE_RUNID=$(date -u +'%Y%m%d-%H%M%S')  # Format without dashes and underscores
          READABLE_DATE=$(date -u +'%B %d, %Y')   # "March 18, 2025"
          echo "runID=$SAFE_RUNID" >> $GITHUB_ENV
          echo "readableDate=$READABLE_DATE" >> $GITHUB_ENV

      - name: Run Cypress tests for ${{ inputs.team }}
        continue-on-error: true
        run: npx cypress run --spec "cypress/e2e/${{ inputs.spec_file }}"

      - name: Setup GitHub Pages directory
        run: |
          mkdir -p gh-pages
          cd gh-pages
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch origin gh-pages --depth=1
          git checkout gh-pages || echo "No gh-pages branch yet"
          cd ..

      - name: Prepare report for GitHub Pages
        run: |
          mkdir -p gh-pages/${{ inputs.team }}/${{ env.runID }}
          cp -r cypress/reports/html/* gh-pages/${{ inputs.team }}/${{ env.runID }}/

      - name: Call Generate Main Index Page Workflow
        uses: ./.github/workflows/generate-main-index-page.yml
        with:
          team: ${{ inputs.team }}

      - name: Call Generate Team Report Page Workflow
        uses: ./.github/workflows/generate-team-report-page.yml
        with:
          team: ${{ inputs.team }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: gh-pages
            keep_files: true
