name: Cypress Main Workflow

on:
  workflow_call:
    inputs:
      spec_file:
        required: true
        type: string
      team:
        required: true
        type: string

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate Readable RunID
        id: runid
        run: |
          # Generate RunID in the desired format (YYYYMMDD-HHMMSS)
          SAFE_RUNID=$(date -u +'%Y%m%d-%H%M%S')  # Format without dashes and underscores
          READABLE_DATE=$(date -u +'%B %d, %Y')   # "March 18, 2025"
          echo "runID=$SAFE_RUNID" >> $GITHUB_ENV
          echo "readableDate=$READABLE_DATE" >> $GITHUB_ENV

      - name: Run Cypress tests for ${{ inputs.team }}
        continue-on-error: true
        run: npx cypress run --spec "cypress/e2e/${{ inputs.spec_file }}"

      - name: Upload Cypress Reports
        uses: actions/upload-artifact@v3
        with:
          name: cypress-reports
          path: cypress/reports/html

      - name: Trigger Report Generation
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'cypress-report.yml',
              ref: context.ref,
              inputs: {
                runID: process.env.runID
              }
            });