name: Cypress Tests for XYZ
concurrency:
  group: "gh-pages-${{ github.ref }}"
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Trigger XYZ Tests'
        required: true
        default: 'yes'

jobs:
  xyz-tests:
    uses: ./.github/workflows/cypress-main.yml
    with:
      spec_file: "xyz_practice-login.cy.js"
      team: "xyz"
