name: Generate Team Report Page Workflow

on:
  workflow_call:
    inputs:
      team:
        required: true
        type: string

jobs:
  generate-team-report-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Team Report Page
        run: |
          for team in abc xyz; do
            echo "<!DOCTYPE html>
            <html>
            <head>
              <title>${team^^} Test Reports</title>
              <style>
                @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap');
                body {
                  font-family: 'Poppins', sans-serif;
                  background-color: #f4f4f9;
                  text-align: center;
                  margin: 0;
                  padding: 0;
                }
                h1 {
                  font-size: 36px;
                  font-weight: 600;
                  color: #222;
                  text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.2);
                  background: linear-gradient(45deg, #17a2b8, #007bff);
                  -webkit-background-clip: text;
                  -webkit-text-fill-color: transparent;
                  margin-top: 20px;
                }
                h2 {
                  font-size: 20px;
                  color: #555;
                  font-weight: 400;
                  opacity: 0.8;
                }
                .container {
                  max-width: 800px;
                  margin: 40px auto;
                  padding: 20px;
                }
                .reports {
                  display: flex;
                  flex-wrap: wrap;
                  justify-content: center;
                  gap: 20px;
                }
                .report-card {
                  width: 280px;
                  height: 100px;
                  background: white;
                  box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);
                  border-radius: 8px;
                  display: flex;
                  flex-direction: column;
                  align-items: center;
                  justify-content: center;
                  font-size: 16px;
                  font-weight: bold;
                  transition: 0.3s;
                  text-decoration: none;
                  color: white;
                  background-color: #28a745;
                  border-left: 5px solid #155724;
                  padding: 10px;
                }
                .report-card:hover {
                  transform: scale(1.05);
                  box-shadow: 0px 4px 12px rgba(0, 0, 0, 0.2);
                  background-color: #218838;
                }
                .timestamp {
                  font-size: 14px;
                  color: #666;
                  margin-top: 4px;
                }
                .back-btn {
                  display: inline-block;
                  margin-top: 20px;
                  padding: 10px 20px;
                  font-size: 14px;
                  text-decoration: none;
                  color: white;
                  background: #007bff;
                  border-radius: 5px;
                  transition: 0.3s;
                }
                .back-btn:hover {
                  background: #0056b3;
                }
              </style>
            </head>
            <body>
              <div class='container'>
                <h1>${team^^} Test Reports</h1>
                <h2>Test Results for ${team^^}</h2>
                <div class='reports'>
                  <div class='report-card'>
                    <span>Run ID: ${team^^}_RUN_ID</span>
                    <span class='timestamp'>${team^^} Test Date</span>
                  </div>
                </div>
                <a href='../index.html' class='back-btn'>Back to Main Page</a>
              </div>
            </body>
            </html>" > gh-pages/${team}/index.html
          done
